theme: jekyll-theme-cayman

baseurl: "/Harperive" # the subpath of your site, e.g. /blog
url: "https://chandan-24.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Aux links for the upper right navigation
aux_links:
  "Harperive on GitHub":
    - "https://github.com/chandan-24/Harperive"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
